name: tofu-version
description: Prints OpenTofu and providers versions
author: Daniel Flook

inputs:
  path:
    description: The path to the OpenTofu root module directory.
    required: false
    default: "."
  workspace:
    description: The workspace to determine the OpenTofu version for.
    required: false
    default: "default"
  backend_config:
    description: |
      List of OpenTofu backend config values, one per line.

      This will be used to fetch the OpenTofu version set in the cloud workspace if using the `remote` backend.
      For other backend types, this is used to fetch the version that most recently wrote to the OpenTofu state.
    required: false
    default: ""
  backend_config_file:
    description: |
      List of OpenTofu backend config files to use, one per line.
      Paths should be relative to the GitHub Actions workspace

      This will be used to fetch the OpenTofu version set in the cloud workspace if using the `remote` backend.
      For other backend types, this is used to fetch the version that most recently wrote to the OpenTofu state.
    required: false
    default: ""

outputs:
  terraform:
    description: The Hashicorp Terraform or OpenTofu version that is used by the configuration.
  tofu:
    description: If the action chose a version of OpenTofu, this will be set to the version that is used by the configuration.

runs:
  env:
    OPENTOFU: true
  using: docker
  image: docker://ghcr.io/dflook/terraform-github-actions@sha256:c322a75fc5586e13b1697cef8e63e6e507a6628125d75f45c6143336fee67652
  entrypoint: /entrypoints/version.sh

branding:
  icon: globe
  color: purple
