name: tofu-version
description: Prints OpenTofu and providers versions
author: Daniel Flook

inputs:
  path:
    description: Path to the OpenTofu configuration
    required: false
    default: .
  workspace:
    description: Name of the OpenTofu workspace to get the version for
    required: false
    default: default
  backend_config:
    description: List of backend config values to set, one per line
    required: false
    default: ""
  backend_config_file:
    description: Path to a backend config file
    required: false
    default: ""

outputs:
  tofu:
    description: The OpenTofu version used by the configuration

runs:
  env:
    OPENTOFU: true
  using: docker
  image: docker://ghcr.io/dflook/terraform-github-actions@sha256:88fd908347b71b91fa2af325114f20ac14c87b7dcb2f8f42294706e5639a7af3
  entrypoint: /entrypoints/version.sh

branding:
  icon: globe
  color: purple
